version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/collector"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/java"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/nodejs"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
  - package-ecosystem: "pip"
    directory: "/python/src/otel/otel_sdk"
    schedule:
      interval: "weekly"
